<?php

define('POPUP_MESSAGE_CSS_NAME', 'popup.css');
define('POPUP_MESSAGE_THEME_STYLE_DIR', 'popup_message_styles');
define('POPUP_MESSAGE_MODULE_STYLE_DIR', 'styles');
define('POPUP_MESSAGE_VISIBILITY_NOTLISTED', 0);
define('POPUP_MESSAGE_VISIBILITY_LISTED', 1);
define('POPUP_MESSAGE_VISIBILITY_MAX', 2);

/**
 * Implements hook_library_info_alter().
 *
 */
function popup_message_library_info_alter(array &$libraries, $extension) {

  $config_popup =  \Drupal::configFactory()->getEditable('popup_message.settings');
  $style = $config_popup->get('style');

  if ($extension === 'popup_message') {
    $libraries['popup_message_style']['css']['module'] = [];
    $libraries['popup_message_style']['css']['module'][POPUP_MESSAGE_MODULE_STYLE_DIR . '/' . $style] = [];
  }
}
